### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by fvpDev** [flemay/Semantic-UI-Meteorize#2]
I'm using Windows...looks like I can't really help after all.

**Comment by fvpDev** [comment]
Ok, I fixed that by replacing all instances of `semantic:ui` with `semantic-ui` wherever folders are concerned (like `base:`, `lib:`) however I'm getting a permission denial (maybe because of private repo, need private RSA key?). See the following:
https://help.github.com/articles/error-permission-denied-publickey/#should-the-sudo-command-be-used-with-git

**Comment by flemay** [comment]
You will need to ask @jlukic to give you access to atmosphere. **Also**, I experienced one issue with the generator: the package version of the package.js files of the 2 packages would not changed. I would just rerun the generator.

**Comment by fvpDev** [comment]
Ok, I'll check out what you mean once I get access from @jlukic

**Comment by flemay** [comment]
Basically, it's just to make sure `dist/semantic:ui/package.js` and `dist/semantic:ui-data/package.js` have the right version before deploying.

**Comment by fvpDev** [comment]
Ok, heard...btw, sorry for my impatience, I know you're busy. There's been a lot of patience-building for me the past week waiting on other people outside of development (job/money-related). It's been an interesting learning experience, learning how to trust that "all will be good". :D Take your time my good sir, no pressure from me.

**Comment by jlukic** [comment]
I've added you @fvpDev to the semantic-org meteor group which should give you admin permissions to those two repos.
